<?php

/**
 * @file
 * Functions to support the layout form.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_form_mode_alter().
 */
function gp_layout_preview_entity_form_mode_alter(&$form_mode, EntityInterface $entity) {
  $is_preview = gp_layout_preview_is_preview();

  if ($entity instanceof NodeInterface && $entity->bundle() === 'page' && $is_preview) {
    $form_mode = 'layout';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function gp_layout_preview_page_attachments_alter(array &$attachments) {
  $is_preview = gp_layout_preview_is_preview();

  // Inject theme styles.
  if ($is_preview) {
    $attachments['#attached']['library'][] = 'gallopinto/global';
  }
}

/**
 * Implements hook_theme().
 *
 * Register theme templates.
 */
function gp_layout_preview_theme() {
  $templates = \Drupal::config('gp_layout_preview.settings')
    ->get('components.paragraph_list');

  return $templates;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function gp_layout_preview_preprocess_html(&$variables) {
  $is_preview = gp_layout_preview_is_preview();

  // Inject theme styles.
  if ($is_preview) {
    $variables['attributes']['class'][] = 'gin--edit-form';
  }
}

/**
 * Validates if route is for the layout preview page.
 */
function gp_layout_preview_is_preview() {
  $route_name = \Drupal::routeMatch()->getRouteName();

  return $route_name === 'gp.layout_preview';
}

function gp_layout_preview_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'gallopinto/update-spacing';
}
