<?php

/**
 * @file
 * Functions to support the layout form.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_entity_form_mode_alter().
 */
function gp_layout_preview_entity_form_mode_alter(&$form_mode, EntityInterface $entity) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  if ($entity instanceof NodeInterface && $entity->bundle() === 'page' && $route_name === 'gp.layout_preview') {
    $form_mode = 'layout';
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function gp_layout_preview_page_attachments_alter(array &$attachments) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  // Inject theme styles.
  if ($route_name === 'gp.layout_preview') {
    $attachments['#attached']['library'][] = 'gallopinto/global';
  }
}

/**
 * Implements hook_theme().
 *
 * Register theme templates.
 */
function gp_layout_preview_theme(array $theme) {
  $templates = \Drupal::config('gp_layout_preview.settings')
    ->get('components.paragraph_list');

  return $templates;
}
